name: cat_breeds_ui
description: Cat Breeds UI
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter_gen:
  output: lib/src/gen/

  integrations:
    flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/imgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/src/typography/fonts/Poppins-Bold.ttf
        - asset: lib/src/typography/fonts/Poppins-Extrabold.ttf
        - asset: lib/src/typography/fonts/Poppins-Light.ttf
        - asset: lib/src/typography/fonts/Poppins-Medium.ttf
        - asset: lib/src/typography/fonts/Poppins-Regular.ttf
        - asset: lib/src/typography/fonts/Poppins-Semibold.ttf

    - family: CatBreed
      fonts:
        - asset: assets/icons/CatBreed.ttf
